name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'Readme.md'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: |
          echo "Checking if secrets are available..."
          echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}"
          echo "Checking Docker Status..."
          docker version

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/application-game:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  owasp-dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Dependency-Check Directory
        run: |
          echo "Checking if dependency-check directory exists..."
          if [ -d "dependency-check" ]; then
            echo "Dependency-Check directory already exists."
          else
            echo "Error: Dependency-Check directory does not exist!" && exit 1
          fi

      - name: Set up OWASP Dependency-Check
        run: |
          echo "Setting up OWASP Dependency-Check..."
          curl -sLO https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check-8.4.0-release.zip -d dependency-check
          echo "Extracting contents..."
          ls -R dependency-check
          chmod +x dependency-check/bin/dependency-check.sh

      - name: List Extracted Files for Debugging
        run: |
          echo "Listing all files in dependency-check directory:"
          find dependency-check

      - name: Run OWASP Dependency-Check
        run: |
          dependency-check/bin/dependency-check.sh --scan . --format "HTML" --out reports

      - name: Upload OWASP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-Dependency-Check-Report
          path: reports/

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: owasp-dependency-check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "omraut0508@gmail.com"
          git config --global user.name "om0508"

      - name: Update Helm Chart Tag
        run: |
          sed -i "s/tag: .*/tag: \"${{ github.run_id }}\"/" application-game-charts/values.yaml

      - name: Commit and Push Changes
        run: |
          git add application-game-charts/values.yaml
          git commit -m "Update tag in Helm chart" || echo "No changes to commit."
          git pull origin main --rebase || git rebase --abort
          git push origin main
